import { writeFileSync } from 'fs';
import { ParsedSchema } from '../types/schema';

/**
 * Generate a TypeScript seed file that can be run independently
 */
export async function generateSeedFile(
  outputPath: string,
  generatedData: Record<string, any[]>,
  insertOrder: string[],
  schema: ParsedSchema
): Promise<void> {
  const template = buildSeedTemplate(generatedData, insertOrder, schema);
  writeFileSync(outputPath, template, 'utf-8');
}

function buildSeedTemplate(
  generatedData: Record<string, any[]>,
  insertOrder: string[],
  schema: ParsedSchema
): string {
  const dataJson = JSON.stringify(generatedData, null, 2);

  return `/**
 * Database Seed File
 * Generated by snapgen - AI-powered database seeding tool
 *
 * Run this file to seed your database with realistic data
 *
 * Usage:
 *   ts-node seed.ts
 *
 * Or with tsx:
 *   tsx seed.ts
 */

import { Pool } from 'pg';

const DATABASE_URL = process.env.DATABASE_URL || 'postgresql://user:password@localhost:5432/dbname';

const generatedData = ${dataJson};

const insertOrder = ${JSON.stringify(insertOrder)};

async function seed() {
  const pool = new Pool({
    connectionString: DATABASE_URL,
    max: 10,
  });

  try {
    console.log('Starting database seeding...');

    let totalInserted = 0;

    for (const tableName of insertOrder) {
      const rows = generatedData[tableName];

      if (!rows || rows.length === 0) {
        console.log(\`Skipping \${tableName} (no data)\`);
        continue;
      }

      console.log(\`Seeding \${tableName} with \${rows.length} rows...\`);

      // Get column names
      const columns = Object.keys(rows[0]);

      // Build INSERT query
      const placeholders: string[] = [];
      const values: any[] = [];

      rows.forEach((row: any, rowIndex: number) => {
        const rowPlaceholders: string[] = [];

        columns.forEach((col: string, colIndex: number) => {
          const paramIndex = rowIndex * columns.length + colIndex + 1;
          rowPlaceholders.push(\`$\${paramIndex}\`);

          let value = row[col];

          // Handle special types
          if (value !== null && value !== undefined) {
            if (typeof value === 'object' && !Array.isArray(value)) {
              value = JSON.stringify(value);
            }
          }

          values.push(value);
        });

        placeholders.push(\`(\${rowPlaceholders.join(', ')})\`);
      });

      const query = \`
        INSERT INTO "\${tableName}" (\${columns.map((c: string) => \`"\${c}"\`).join(', ')})
        VALUES \${placeholders.join(', ')}
        ON CONFLICT DO NOTHING
      \`;

      try {
        const result = await pool.query(query, values);
        const inserted = result.rowCount || 0;
        totalInserted += inserted;
        console.log(\`  ✓ Inserted \${inserted} rows into \${tableName}\`);
      } catch (error) {
        console.error(\`  ✖ Failed to insert into \${tableName}:\`, error);
      }
    }

    console.log(\`\\n✓ Seeding completed! Total rows inserted: \${totalInserted}\`);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

seed();
`;
}
